### PR TITLE
Fix dns_suffix option

### PR DESCRIPTION
**Pull request by 71FIL**
- option was being parsed and used as a boolean
- add support in cluster configuration file
- suffix has two 'f'

### CODE REVIEW

**Comment by FinchPowers** [comment]
Hey! This looks like a legitimate fix. Why did you close the request? Is it because of the failed Travis Build?

**Comment by FinchPowers** [comment]
Duplicate https://github.com/datacratic/StarCluster/pull/25 https://github.com/datacratic/StarCluster/pull/26

**Comment by 71FIL** [comment]
Yes, closed it because it was failing the travis build. I was just about to do it again. I tried to reproduce the pep8 failures here but to no avail: it passes here.

**Comment by FinchPowers** [comment]
Ok. you don't need to close it. If you push another commit the test are rerun.
I'll have a look at the failure.
Thanks :)

**Comment by 71FIL** [comment]
Duplicate #27

**Pull request closed without merging**
