### PR TITLE
Fix dns_suffix option

### PR DESCRIPTION
**Pull request by 71FIL**
- option was being parsed and used as a boolean
- add support in cluster configuration file
- suffix has two 'f'

### CODE REVIEW

**Comment by 71FIL** [comment]
I was about to do the extra fix here, I can still do it. Do you have any idea why pep8 would not detect the problem in my environment?

**Comment by FinchPowers** [comment]
Yes do it here. :)
Your environment may be "outdated". Travis always takes the latest version I think so something new may have came up.

**Comment by 71FIL** [comment]
There might be a few more iterations... Hopefully not.

**Comment by FinchPowers** [comment]
Please stop closing/reopening the PR! :) It doesn't make Travis more likely to succeed and spread the discussion across many pages.

**Pull request closed without merging**
