### PR TITLE
Allow aws_access_key_id and aws_secret_access_key to be left blank

### PR DESCRIPTION
**Pull request by cancan101**
boto will then employ it's own resolution mechanism allowing the user to specify in config file or env var.

### CODE REVIEW

**Comment by FinchPowers** [comment]
If the keys are not defined in the "boto way", is the error clear?

**Comment by cancan101** [comment]
I think it will fall back to boto barfing with something like:
```
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

**Comment by FinchPowers** [comment]
Do you think it would be worth it then to handle the error to print a message telling the 2 ways StarCluster can support keys?

**Comment by cancan101** [comment]
Seems overkill to me. Also not sure of all the points to catch this error and re-throw.

**Comment by vasisht** [comment]
@cancan101 Just out of curiosity, what's the use case for leaving the credentials blank?

**Comment by cancan101** [comment]
So i don't have to put my creds into config file (and I can source control it)

**Pull request merged**
